# Linked app "r1" — bundle sync + checkout handoff
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07c05f70918264669a4ee35d47dce99f"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false
name = "r1"

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "tiyndf-za.myshopify.com"
